### ISSUE TITLE
Ioc

### ISSUE THREAD

**Issue by ShahramNo** [babaktaremi/Clean-Architecture-Template#5]
hi, 
I need Ioc in this repo, my question is why autofac not used?
for example IemailSender or ISmsSeender must register manually,
second question   where is correct place of dto or viewModel? and how we can automapper like mr Ebrahimi repo?

**Comment by babaktaremi** [comment]
I didn't use autofac because the default ASP NET Core IOC service is more than enough. Also with autofac you can easily violate some of dependency injection rules (such as inheritance security rules) and it's overall performance is really bad.
The part of your question related to View Models and DTOs, obviously the best place to put your View Models is in API Layer, for DTOs I would prefer the term of Application Models which should be put in Application layer.
About using automapper, There is an generic interface in each layer called ICreateMapper<TModel> in which TModel is the destination model that you want to map your current model to. It uses default Interface implementation feature introduced in C# 8 and does the mapping configuration automatically for you but if you need to configure it manually, you simply implement the map method of ICreateMapper interface yourself

**Comment by ShahramNo** [comment]
thanks a lot
